spring:
  application:
    name: OnlineFilePreview
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /**
  resources:
    static-locations: /,classpath:/resources/,classpath:/static/
server:
  port: 8088

# Libre Office 的 bin 目录
libre-office:
  bin:
    file-path: D:/Program Files/LibreOffice/program/soffice.bin

file:
  office-to-pdf-command: ${libre-office.bin.file-path} --headless --invisible --convert-to %s %s --outdir %s